version: '3'

services:
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`10.10.1.101`)"
            - "traefik.http.routers.nginx.entrypoints=web"
        networks:
            - network-test

networks:
   network-test:
     external: true
